spring:
  application:
    name: basic-server
server:
  port: 4000
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:server.p12
    key-store-password: 12345678
    key-alias: server
    trust-store-type: JKS
    trust-store: classpath:truststore.jks
    trust-store-password: 12345678
    client-auth: need